JavaScript capstone project - Your API-based webapp
Sboursen/MV-Module2-capstone pull request #47
Opened 2022-03-11 14:37 UTC by Sboursen

## Description

> **CarCollectors** is website made for users that are interested in renting a car. It allows the visitor to browse an extensive collection of beautiful cars using the [Cars API](https://carsapi1.docs.apiary.io/#reference/0/cars-collection). It also allows the user to like, comment and make a reservation for a given car. All data are saved thanks the [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270).

### General requirements

- [x] There are no linter errors.
- [x] Followed the **Github flow**.
- [x] The documentation is professional.

### HTML/CSS and JavaScript requirements

- [x] Followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [x] Followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md)

### Capstone project requirements

### Built With

![](https://img.shields.io/badge/HTML-5-orange) ![](https://img.shields.io/badge/Tailwind-CSS-blue) ![](https://img.shields.io/badge/JavaScript-ES6-yellow) ![](https://img.shields.io/badge/Webpack-5-green) ![](https://img.shields.io/badge/JEST-27-yellow)

### Milestones

- [x] Milestone 1: **Project Setup and topic.**
- [x] Milestone 2: **Creation of the Home interface. Creation of the comment and the reservation pop-ups**
- [x] Milestone 3: **Creation of the communication interfaces with the APIs**
- [x] Milestone 4: **Implementation of the likes, comments and the reservations functionalities**
- [x] Milestone 5: **Writing tests to ensure the robustness of the application**

### Additional notes

> We apologize for the submission delays. It was due to some difficulties handling the **Cars API**.

> We made a [video demo](https://drive.google.com/file/d/1cjoWow9qx2MITazNmDSKM9TQczIT64aw/view?usp=sharing) for our website.

**_Thank you for taking the time to review this pull request._**
### Happy reviewing :grinning:

2022-03-11 17:04 UTC, mikethreels requested changes
Hi Team, 

Good job setting up the api calls and making them work 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] The video should contain a highlight about a piece of the code you find interesting or are proud of making, please reshoot the video and include this

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] [OPTIONAL] It would be nice to see all the authors of the project with their camera on in the video presentation.
- [ ] [OPTIONAL] The dislike is not persisting it would be nice if this is the case.
- [ ] [OPTIONAL] when adding a comment or a reservation if the fields are empty the user is still able to add it it would be nice if you add the functionality so that the user is required to fill in the fields before they are able to submit it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 17:04 UTC, mikethreels commented on src/index.js
> +function registerHomeEvents() {
- [ ] according to the requirements the Project should use ES6, which means you should avoid usage of the function keyword, please use arrow functions instead.

2022-03-11 17:04 UTC, mikethreels commented on src/modules/comments/comments-app.js
> +export async function showCommentModal(e) {
- [ ] according to the requirements the Project should use ES6, which means you should avoid usage of the function keyword, please use arrow functions instead.

2022-03-11 17:04 UTC, mikethreels commented on src/modules/home/home-app.js
> +export function getAllCarsCount() {
- [ ] according to the requirements the Project should use ES6, which means you should avoid usage of the function keyword, please use arrow functions instead.

2022-03-11 17:04 UTC, mikethreels commented on src/modules/home/home-utils.js
> +export function fileExists(imageUrl) {
- [ ] according to the requirements the Project should use ES6, which means you should avoid usage of the function keyword, please use arrow functions instead.

2022-03-11 17:04 UTC, mikethreels commented on src/modules/reservations/reservation-app.js
> +export default function showReservationModal(e) {
- [ ] according to the requirements the Project should use ES6, which means you should avoid usage of the function keyword, please use arrow functions instead.

2022-03-11 18:41 UTC, Sboursen commented
Hi @mikethreels, :wave: 

First, we would like to thank you for the extensive feedback. :pray: 

As for the requested changes: 

- [x] we have successfully changed all our functions to use only ES6 syntax (AKA arrow functions).

- [x] We added a new feature `The loader`, that is being shown when the cars are being fetched from the Cars API.

- [x] We made a new video, that shows us giving a demo of the project.

- [x] Unfortunately we can not make the dislike feature persistent, because there is now way to delete likes from the Involvement API.

- [x] We would like to leave the validation feature to next release as it's not required right now.

Best,

2022-03-11 18:48 UTC, Lordkaito approved these changes
Hi @Sboursen and @jerryowusu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 19:27 UTC, Sboursen commented
Hi @Lordkaito 👋 

Thank  you for the approval.

Best,

2022-03-11 19:27 UTC, merged

2022-03-11 20:35 UTC, jerryowusu commented
Thanks a lot @Lordkaito for the swift response and approval. (we were a group of 3 though, which includes @mwafrika)

2022-03-11 20:40 UTC, jerryowusu commented
Congratulations @Sboursen and @mwafrika, it wasn't easy but we sailed through


![200w](https://user-images.githubusercontent.com/65233860/157959195-1beeaf6e-32b1-4bb4-981f-72c1284d6bf5.gif)
.

2022-03-11 21:33 UTC, Sboursen commented
Yes we did

2022-03-12 06:21 UTC, mwafrika commented
Yes we did it for sure, @Sboursen  @Sboursen  and me congratulations 🥇 🥇 🥇 
It was not easy